In [1]:
print(2)

2


In [1]:
import numpy as np

In [11]:
a = np.array([1, 2, 3], dtype='int16')
print(a)

[1 2 3]


In [4]:
b = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [6]:
#Get dimensions
a.ndim

1

In [7]:
b.ndim

2

In [8]:
a.shape

(3,)

In [9]:
b.shape

(2, 3)

In [12]:
a.dtype

dtype('int16')

In [13]:
b.dtype

dtype('float64')

In [15]:
a.itemsize #2bytes

2

In [20]:
#Indexing

In [4]:
c = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [5]:
c.shape

(2, 7)

In [8]:
c[1, 5]

np.int64(13)

In [9]:
c[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
c[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [11]:
c[:, 0]

array([1, 8])

In [15]:
c[0, 1:6:2]

array([2, 4, 6])

In [16]:
c[1, 6] = 24
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 24]]


In [17]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
d[0, 1, 1]

np.int64(4)

In [19]:
d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [21]:
#Different types of array

In [24]:
np.zeros((2, 4, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [26]:
np.ones((2, 2), dtype='int32')

array([[1, 1],
       [1, 1]], dtype=int32)

In [27]:
np.full((3, 3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [29]:
np.full_like(c, 77)

array([[77, 77, 77, 77, 77, 77, 77],
       [77, 77, 77, 77, 77, 77, 77]])

In [32]:
np.full(c.shape, 77)

array([[77, 77, 77, 77, 77, 77, 77],
       [77, 77, 77, 77, 77, 77, 77]])

In [33]:
np.random.rand(3, 2)

array([[0.28466578, 0.84678189],
       [0.50434056, 0.26560213],
       [0.45375422, 0.68213791]])

In [7]:
np.random.randint(2,10, size=(3, 3))

array([[4, 7, 6],
       [7, 3, 4],
       [2, 7, 6]])

In [8]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [12]:
q = np.array([[1, 1, 1, 1, 1], [1, 0, 0, 0, 1], [1, 0, 9, 0, 1],  [1, 0, 0, 0, 1], [1, 1, 1, 1, 1]])
print(q)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [15]:
ans = np.ones((5, 5), dtype='int64')
print(ans)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [18]:
ans[1:4, 1:4] = 0
print(ans)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [19]:
ans[2, 2] = 9
print(ans)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


##### Be careful when copying arrays!!!

In [25]:
a = np.array([1, 2, 3])
b = a
c = a.copy()
b[0] = 100
c[0] = 200
print(b)
print(a)
print(c)
print(a)

[100   2   3]
[100   2   3]
[200   2   3]
[100   2   3]


##### Mathematics

In [2]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [3]:
a+2

array([3, 4, 5, 6])

In [4]:
a-2

array([-1,  0,  1,  2])

In [5]:
a*2

array([2, 4, 6, 8])

In [6]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [7]:
b = np.array([1, 0, 1, 0])

In [8]:
a+b

array([2, 2, 4, 4])

In [9]:
a**2

array([ 1,  4,  9, 16])

In [10]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

##### Linear Algebra

In [13]:
a = np.full((2, 3), 2)
a

b = np.full((3, 2), 3)
b

np.matmul(a, b)

array([[18, 18],
       [18, 18]])

In [14]:
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

##### Statistics

In [15]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
np.min(stats)

np.int64(1)

In [17]:
np.max(stats)

np.int64(6)

In [18]:
np.sum(stats)

np.int64(21)

##### Reorganizing arrays

In [5]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

after = before.reshape((4, 2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [9]:
#Vertical stacking
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
#Horizontal stacking
hp1 = np.ones((2, 4))
hp2 = np.zeros((2, 2))

np.hstack((hp1, hp2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

##### Miscellaneous

In [14]:
filedata = np.genfromtxt('data.txt', delimiter=",")
filedata.astype('int32')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

##### Boolean Masking and Advanced Indexing

In [15]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [16]:
filedata[filedata > 50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [17]:
#You can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])